-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTcKYC+kSU/NDJXzK
8+h2+KuuYhU1HNLRALCtUZn7MaOgCgYIKoZIzj0DAQehRANCAAQF++dv/Ck7D+O8
smoCOk0wYGyT4nM3gEJZSvMSeQcQG1O4ZFpMlGSAhZkxx5ROw3DNyNr83OfVnir/
18f6J3R3
-----END PRIVATE KEY-----